#ifndef options_h
#define options_h
#pragma once

#define FW_VERSION "0.1.5_MB"

#ifndef THEME_CSV_VERSION
#    define THEME_CSV_VERSION "0.0.1"
#endif

/*******************************************************
DO NOT EDIT THIS FILE.
ALL YOUR SETTINGS WILL BE OVERWRITTEN DURING THE UPDATE.
STORE YOUR SETTINGS IN THE *** myoptions.h *** FILE.
********************************************************/

#if __has_include("../../myoptions.h")
#    include "../../myoptions.h" /* <- write your variable values here */
#endif

#if __has_include("../../mytheme.h")
#    include "../../mytheme.h" /* <- Theme file */
#endif

#if __has_include("../../mqttoptions.h")
#    include "../../mqttoptions.h"
#endif

#ifndef BOOTLOG
#    define BOOTLOG(...)                                               \
        do {                                                           \
            char _bootlog_buf[120];                                    \
            snprintf(_bootlog_buf, sizeof(_bootlog_buf), __VA_ARGS__); \
            Serial.printf("##[BOOT]#\t%s\n", _bootlog_buf);            \
        } while (0)
#endif

// clang-format off
#define DSP_DUMMY       0     // without display
#define DSP_ST7735      1     // 160x128  1.8'  or 128x128  1.44'  or 160x80   0.96'  https://aliexpress.com/item/1005002822797745.html
#define DSP_SSD1306     2     // 128x64   0.96' https://aliexpress.com/item/1005001621806398.html
#define DSP_ST7789      4     // 320x240  2.4'  https://aliexpress.com/item/32960241206.html 
#define DSP_SH1106      5     // 128x64   1.3'  https://aliexpress.com/item/32683094040.html
#define DSP_SSD1327     8     // 128x128  1.5'  https://aliexpress.com/item/1005001414175498.html
#define DSP_ILI9341     9     // 320x240  3.2'  https://aliexpress.com/item/33048191074.html
#define DSP_SSD1305     10    // 128x64   2.4'  SSD1305 and SSD1309 SPI https://aliexpress.com/item/32950307344.html
#define DSP_SSD1305I2C  16    // 128x64   2.4'  SSD1305 and SSD1309 I2C https://aliexpress.com/item/32950307344.html
#define DSP_ILI9225     17    // 220x176  2.0'  https://aliexpress.com/item/32952021835.html
#define DSP_ST7789_240  18    // 240x240  1.3'  https://aliexpress.com/item/32996979276.html
#define DSP_ST7796      19    // 480x320  3.5'  https://aliexpress.com/item/1005004632953455.html?sku_id=12000029911293172
#define DSP_GC9A01A     20    // 240x240  1.28' https://aliexpress.com/item/1005004069703494.html?sku_id=12000029869654615
#define DSP_ILI9488     21    // 480x320  3.5'  https://aliexpress.com/item/1005001999296476.html?sku_id=12000018365356570
#define DSP_ILI9486     22    // (Testing mode) 480x320  3.5'  https://aliexpress.com/item/1005001999296476.html?sku_id=12000018365356568
#define DSP_SSD1322     23    // 256x64   2.8'  https://aliexpress.com/item/1005003480981568.html
#define DSP_ST7920      24    // 128x64   2.6'  https://aliexpress.com/item/32699482638.html
#define DSP_ST7789_76   25    // 284x76   2.25' https://aliexpress.com/item/1005009016973081.html
#define DSP_2002        26    // 20x2           https://aliexpress.com/item/32812259852.html
#define DSP_2002I2C     27    // 20x2           https://aliexpress.com/item/32812259852.html
#define DSP_ST7789_170  28    // 320x170  1.9'  https://aliexpress.com/item/1005008723378017.html

#define TS_MODEL_UNDEFINED      0
#define TS_MODEL_XPT2046        1
#define TS_MODEL_GT911          2
#define TS_MODEL_FT6X36         3
#define TS_MODEL_AXS15231B      4

#ifndef DSP_MODEL
  #define DSP_MODEL  DSP_DUMMY
#endif

#ifndef LED_INVERT
  #define LED_INVERT   false      // invert onboard LED?
#endif

#ifndef POWER_LED
  #define POWER_LED 255      // Button LED pin (will be turned on when player is on)
#endif


/*        TFT DISPLAY             */
#ifndef DEFAULT_SCREEN_ROTATION
  #if DSP_MODEL == DSP_ST7796
    #define DEFAULT_SCREEN_ROTATION 3
  #elif DSP_MODEL == DSP_ILI9488
    #define DEFAULT_SCREEN_ROTATION 1
  #else
    #define DEFAULT_SCREEN_ROTATION 1
  #endif
#endif

#ifndef LGFX_LCD_SPI_HOST
  #define LGFX_LCD_SPI_HOST     2  // 1=HSPI, 2=VSPI (ESP32 only)
#endif

#ifndef TFT_DC
  #define TFT_DC        9
#endif
#ifndef TFT_CS
  #define TFT_CS        10
#endif
#ifndef TFT_RST
  #define TFT_RST       -1   // Or set to -1 and connect to Esp EN pin
#endif

/*        NEXTION                 */
#ifndef NEXTION_RX
  #define NEXTION_RX    255
#endif
#ifndef NEXTION_TX
  #define NEXTION_TX    255
#endif
#if NEXTION_RX!=255 && NEXTION_TX!=255
  #define USE_NEXTION
#endif
/*        OLED I2C DISPLAY        */
#ifndef I2C_SDA
  #define I2C_SDA 21
#endif
#ifndef I2C_SCL
  #define I2C_SCL 22
#endif
#ifndef I2C_RST
  #define I2C_RST -1
#endif

/*        I2S DAC                 */
#ifndef I2S_DOUT
  #define I2S_DOUT      4  // DIN connection
#endif
#ifndef I2S_BCLK
  #define I2S_BCLK      5  // BCLK Bit clock
#endif
#ifndef I2S_LRC
  #define I2S_LRC       6  // WSEL Left Right Clock
#endif
#ifndef I2S_MCLK
  #define I2S_MCLK      -1  // MCLK (Master Clock) - only needed for DACs like CS4344; -1 = unused
#endif

/*        SDCARD                  */
#ifndef SDC_CS
  #define SDC_CS        255  // SDCARD CS pin
#endif
#if SDC_CS!=255
  #define USE_SD
#endif
/*        ENCODER                 */
#ifndef ENC_BTNL
  #define ENC_BTNL              255
#endif
#ifndef ENC_BTNB
  #define ENC_BTNB              255
#endif
#ifndef ENC_BTNR
  #define ENC_BTNR              255
#endif
#ifndef ENC_INTERNALPULLUP                // Thanks for Buska1968. See this topic: https://4pda.to/forum/index.php?s=&showtopic=1010378&view=findpost&p=113385448
  #define ENC_INTERNALPULLUP    true
#endif
#ifndef ENC_HALFQUARD
  #define ENC_HALFQUARD         false
#endif

#ifndef ENC2_BTNL
  #define ENC2_BTNL              255
#endif
#ifndef ENC2_BTNB
  #define ENC2_BTNB              255
#endif
#ifndef ENC2_BTNR
  #define ENC2_BTNR              255
#endif
#ifndef ENC2_INTERNALPULLUP
  #define ENC2_INTERNALPULLUP    true
#endif
#ifndef ENC2_HALFQUARD
  #define ENC2_HALFQUARD         false
#endif

/*        BUTTONS                 */
#ifndef BTN_LEFT
  #define BTN_LEFT              255
#endif
#ifndef BTN_CENTER
  #define BTN_CENTER            255
#endif
#ifndef BTN_RIGHT
  #define BTN_RIGHT             255
#endif
#ifndef BTN_UP
  #define BTN_UP            255
#endif
#ifndef BTN_DOWN
  #define BTN_DOWN             255
#endif
#ifndef BTN_MODE
  #define BTN_MODE             255
#endif
#ifndef BTN_INTERNALPULLUP
  #define BTN_INTERNALPULLUP    true
#endif
#ifndef BTN_LONGPRESS_LOOP_DELAY
  #define BTN_LONGPRESS_LOOP_DELAY    200   // delay between calling DuringLongPress event
#endif
#ifndef BTN_CLICK_TICKS
  #define BTN_CLICK_TICKS    300
#endif
#ifndef BTN_PRESS_TICKS
  #define BTN_PRESS_TICKS    500
#endif

/*        TOUCH SCREEN            */
#ifndef TS_MODEL
  #define TS_MODEL              TS_MODEL_UNDEFINED
#endif

#ifndef TS_CS
  #define TS_CS                 3
#endif
#ifndef TS_SDA
  #define TS_SDA                8
#endif
#ifndef TS_SCL
  #define TS_SCL                7
#endif
#ifndef TS_INT
  #define TS_INT                17
#endif
#ifndef TS_RST
  #define TS_RST                255
#endif
#ifndef TS_I2C_PORT
  #define TS_I2C_PORT           0
#endif
#ifndef TS_I2C_ADDR
  #define TS_I2C_ADDR           0x38
#endif

/*        LCD DISPLAY            */
#ifndef LCD_RS
  #define LCD_RS                255
#endif
#ifndef LCD_E
  #define LCD_E                 255
#endif
#ifndef LCD_D4
  #define LCD_D4                255
#endif
#ifndef LCD_D5
  #define LCD_D5                255
#endif
#ifndef LCD_D6
  #define LCD_D6                255
#endif
#ifndef LCD_D7
  #define LCD_D7                255
#endif

/*        RTC                     */
#define RTC_MODULE_UNDEFINED    0
#define DS3231                  1
#define DS1307                  2

#ifndef RTC_MODULE
  #define RTC_MODULE            RTC_MODULE_UNDEFINED  /*  DS3231 or DS1307  */
#endif
#ifndef RTC_SDA
  #define RTC_SDA               255
#endif
#ifndef RTC_SCL
  #define RTC_SCL               255
#endif

/*        ESP DEVBOARD            */
#if defined(ARDUINO_ESP32S3_DEV) || defined(ARDUINO_ESP32C3_DEV)

#define ESP_S3C3 1

#ifndef LED_BUILTIN_S3
#define LED_BUILTIN_S3 255
#endif

#ifndef USE_BUILTIN_LED
#define USE_BUILTIN_LED true
#endif

#if USE_BUILTIN_LED
#define REAL_LEDBUILTIN LED_BUILTIN
#else
#define REAL_LEDBUILTIN LED_BUILTIN_S3
#endif

#else

#ifndef LED_BUILTIN
#define LED_BUILTIN 255
#endif

#define REAL_LEDBUILTIN LED_BUILTIN

#endif
/*        Other settings. You can overwrite them in the myoptions.h file        */
#ifndef NAMEDAYS_FILE
  #define NAMEDAYS_FILE HU  // Namedays file for the selected language. Supported languages: HU, PL, NL, GR, DE (UA Local/namedays/namedays_UA.h is not filled in.)
#endif
#ifndef MUTE_PIN
  #define MUTE_PIN      255   // MUTE Pin
#endif
#ifndef MUTE_VAL
  #define MUTE_VAL      HIGH  // Write this to MUTE_PIN when player is stopped
#endif
#ifndef MUTE_LOCK
  #define MUTE_LOCK      false  // for vs1053 Shield rev2 - lock MUTE_PIN to !MUTE_VAL
#endif
#ifndef BRIGHTNESS_PIN
  #define BRIGHTNESS_PIN 255   // BRIGHTNESS Pin
#endif
#ifndef PLAYER_FORCE_MONO
  #define PLAYER_FORCE_MONO      false  // mono option - false stereo, true mono
#endif
#ifndef I2S_INTERNAL
  #define I2S_INTERNAL      false  // If true - use esp32 internal DAC
#endif
#ifndef ROTATE_90
  #define ROTATE_90         false  // Optional 90 degree rotation for square displays
#endif

#ifndef LIGHT_SENSOR
  #define LIGHT_SENSOR  255   // Light sensor
#endif
#ifndef AUTOBACKLIGHT
  #ifndef AUTOBACKLIGHT_MAX
    #define AUTOBACKLIGHT_MAX          2500
  #endif
  #ifndef AUTOBACKLIGHT_MIN
    #define AUTOBACKLIGHT_MIN          12
  #endif
  #define AUTOBACKLIGHT(x) ({uint16_t _lh=(x>AUTOBACKLIGHT_MAX?AUTOBACKLIGHT_MAX:x); map(_lh, AUTOBACKLIGHT_MAX, 0, AUTOBACKLIGHT_MIN, 100);})  // autobacklight function
#endif
#ifndef DSP_INVERT_TITLE
  #define DSP_INVERT_TITLE  true   // Invert title colors for displays ?
#endif
#ifndef EXT_WEATHER
  #define EXT_WEATHER       true   // Extended weather
#endif
#ifndef RSSI_DIGIT
  #define RSSI_DIGIT       false   // Extended weather
#endif
#ifndef RSSI_STEPS
  #define RSSI_STEPS       -50,-60,-70,-80
#endif

/*------------------ CLOCK FONTS -----------------*/
#define CLOCKFONT_STYLE_DIGI7 0
#define CLOCKFONT_STYLE_CALIBRI 1
#define CLOCKFONT_STYLE_ANDROIDCLOCK 2

#ifndef CLOCKFONT_STYLE
  #define CLOCKFONT_STYLE CLOCKFONT_STYLE_DIGI7
#endif
#ifndef CLOCKFONT_MONO_DEFAULT
#  ifdef CLOCKFONT_MONO
#    define CLOCKFONT_MONO_DEFAULT true
#  else
#    define CLOCKFONT_MONO_DEFAULT false
#  endif
#endif
#ifndef CLOCK_AM_PM_STYLE_DEFAULT
#  ifdef AM_PM_STYLE
#    define CLOCK_AM_PM_STYLE_DEFAULT true
#  else
#    define CLOCK_AM_PM_STYLE_DEFAULT false
#  endif
#endif

#ifndef MAX_AUDIO_SOCKET_TIMEOUT
  #define MAX_AUDIO_SOCKET_TIMEOUT   false     // max audio socket timeout?
#endif
#ifndef BITRATE_FULL
  #define BITRATE_FULL     true   // display bitreta badget
#endif
#ifndef SD_AUTOPLAY
  #define SD_AUTOPLAY      true   // auto play from SD card when inserted
#endif
#ifndef SD_MAX_LEVELS
  #define SD_MAX_LEVELS      3      //  search depth for files on the SD card
#endif

#ifndef DTYPE
  #define DTYPE INITR_BLACKTAB
#endif

/*---------------- IR -----------------*/
#ifndef IR_PIN
  #define IR_PIN                255
#endif
#ifndef IR_TIMEOUT
  #define IR_TIMEOUT            80        // kTimeout, see IRremoteESP8266 documentation
#endif
#ifndef IR_BUFSIZE
  #define IR_BUFSIZE            128
#endif
#ifndef IR_WAKE_MIN_PULSES
#define IR_WAKE_MIN_PULSES 130
#endif
#ifndef IR_WAKE_CHECK_TIME
#define IR_WAKE_CHECK_TIME 200   // ms
#endif
#ifndef WAKE_PIN1
  #define WAKE_PIN1     255   // Wake Pin (for manual wakeup from sleep mode. can match with BTN_XXXX, ENC_BTNB, ENC2_BTNB. 
#endif
#ifndef WAKE_PIN2
  #define WAKE_PIN2     255   // Wake Pin (for manual wakeup from sleep mode. can match with BTN_XXXX, ENC_BTNB, ENC2_BTNB.  
#endif




/*        THEMES                                 */
/*        color name               R    G    B   */
#ifndef COLOR_BACKGROUND
  #define COLOR_BACKGROUND          0,   0,   0
#endif
#ifndef COLOR_STATION_NAME
  #define COLOR_STATION_NAME        0,   0,   0
#endif
#ifndef COLOR_STATION_BG
  #define COLOR_STATION_BG        231, 211,  90
#endif
#ifndef COLOR_STATION_FILL
  #define COLOR_STATION_FILL      231, 211,  90
#endif
#ifndef COLOR_SNG_TITLE_1
  #define COLOR_SNG_TITLE_1       255, 255, 255
#endif
#ifndef COLOR_SNG_TITLE_2
  #define COLOR_SNG_TITLE_2       165, 162, 132
#endif
#ifndef COLOR_WEATHER
  #define COLOR_WEATHER           255, 150,   0
#endif
#ifndef COLOR_CLOCK
  #define COLOR_CLOCK             231, 211,  90
#endif
#ifndef COLOR_CLOCK_BG
  #define COLOR_CLOCK_BG           28,  28,  28
#endif
#ifndef COLOR_SECONDS
  #define COLOR_SECONDS           231, 211,  90
#endif
#ifndef COLOR_NAMEDAY_LABEL
  #define COLOR_NAMEDAY_LABEL     165, 162, 132
#endif
#ifndef COLOR_NAMEDAY
  #define COLOR_NAMEDAY           255, 200, 100
#endif
#ifndef COLOR_DATE
  #define COLOR_DATE              165, 162, 132
#endif
#ifndef COLOR_BUFFER
  #define COLOR_BUFFER            165, 162, 132
#endif
#ifndef COLOR_IP
  #define COLOR_IP                165, 162, 132
#endif
#ifndef COLOR_IP_BG
  #define COLOR_IP_BG               0,   0,   0
#endif
#ifndef COLOR_IP_BORDER
  #define COLOR_IP_BORDER         102, 178, 255
#endif
#ifndef COLOR_CH
  #define COLOR_CH                165, 162, 132
#endif
#ifndef COLOR_CH_BG
  #define COLOR_CH_BG               0,   0,   0
#endif
#ifndef COLOR_CH_BORDER
  #define COLOR_CH_BORDER         102, 178, 255
#endif
#ifndef COLOR_RSSI
  #define COLOR_RSSI              165, 162, 132
#endif
#ifndef COLOR_RSSI_BG
  #define COLOR_RSSI_BG             0,   0,   0
#endif
#ifndef COLOR_RSSI_BORDER
  #define COLOR_RSSI_BORDER       102, 178, 255
#endif
#ifndef COLOR_DIGITS
  #define COLOR_DIGITS            255, 255, 255
#endif
#ifndef COLOR_DIVIDER
  #define COLOR_DIVIDER           165, 162, 132
#endif
#ifndef COLOR_PL_CURRENT
  #define COLOR_PL_CURRENT          0,   0,   0
#endif
#ifndef COLOR_PL_CURRENT_BG
  #define COLOR_PL_CURRENT_BG     231, 211,  90
#endif
#ifndef COLOR_PL_CURRENT_FILL
  #define COLOR_PL_CURRENT_FILL   231, 211,  90
#endif
#ifndef COLOR_PLAYLIST_0
  #define COLOR_PLAYLIST_0        115, 115, 115
#endif
#ifndef COLOR_PLAYLIST_1
  #define COLOR_PLAYLIST_1         89,  89,  89
#endif
#ifndef COLOR_PLAYLIST_2
  #define COLOR_PLAYLIST_2         56,  56,  56
#endif
#ifndef COLOR_PLAYLIST_3
  #define COLOR_PLAYLIST_3         35,  35,  35
#endif
#ifndef COLOR_PLAYLIST_4
  #define COLOR_PLAYLIST_4         25,  25,  25
#endif
#ifndef COLOR_BITRATE
  #define COLOR_BITRATE           231, 211,  90
#endif
#ifndef COLOR_PRST_BUTTON
  #define COLOR_PRST_BUTTON        14,  21,  30
#endif
#ifndef COLOR_PRST_CARD
  #define COLOR_PRST_CARD          14,  21,  30
#endif
#ifndef COLOR_PRST_ACCENT
  #define COLOR_PRST_ACCENT         0,  76, 153
#endif
#ifndef COLOR_PRST_FAV
  #define COLOR_PRST_FAV          255, 150,   0
#endif
#ifndef COLOR_PRST_TITLE_1
  #define COLOR_PRST_TITLE_1      255, 255, 255
#endif
#ifndef COLOR_PRST_TITLE_2
  #define COLOR_PRST_TITLE_2      200, 200, 200
#endif
#ifndef COLOR_PRST_TITLE_3
  #define COLOR_PRST_TITLE_3      150, 150, 150
#endif
#ifndef COLOR_PRST_LINE
  #define COLOR_PRST_LINE         162, 162, 162
#endif
/*----- VU WIDGET -----*/
#ifndef COLOR_VU_MAX
  #define COLOR_VU_MAX            231, 211,  90
#endif
#ifndef COLOR_VU_MID
  #define COLOR_VU_MID            255, 255, 0
#endif
#ifndef COLOR_VU_MIN
  #define COLOR_VU_MIN            123, 125, 123
#endif
#ifndef COLOR_VU_LRBOX
  #define COLOR_VU_LRBOX          125, 125, 125
#endif
#ifndef COLOR_VU_LRTEXT
  #define COLOR_VU_LRTEXT         255, 255, 255
#endif
/*----- VOLUME WIDGET -----*/
#ifndef COLOR_VOL_BG
  #define COLOR_VOL_BG              0,   0,   0
#endif
#ifndef COLOR_VOL_BORDER
  #define COLOR_VOL_BORDER        102, 178, 255
#endif
#ifndef COLOR_VOL_LOW
  #define COLOR_VOL_LOW             0, 255,   0
#endif
#ifndef COLOR_VOL_MID
  #define COLOR_VOL_MID           255, 255,   0
#endif
#ifndef COLOR_VOL_HIGH
  #define COLOR_VOL_HIGH          255,   0,   0
#endif
#ifndef COLOR_VOL_INACTIVE
  #define COLOR_VOL_INACTIVE       50,  50,  50
#endif
#ifndef COLOR_VOL_ICON
  #define COLOR_VOL_ICON          255, 255, 255
#endif
/*----- WIFI WIDGET -----*/
#ifndef COLOR_WIFI_BG
  #define COLOR_WIFI_BG             0,   0,   0
#endif
#ifndef COLOR_WIFI_BORDER
  #define COLOR_WIFI_BORDER       102, 178, 255
#endif
#ifndef COLOR_WIFI_INACTIVE
  #define COLOR_WIFI_INACTIVE      50,  50,  50
#endif
#ifndef COLOR_WIFI_LOW
  #define COLOR_WIFI_LOW          255,   0,   0
#endif
#ifndef COLOR_WIFI_LOW_MID
  #define COLOR_WIFI_LOW_MID      255, 140,   0
#endif
#ifndef COLOR_WIFI_MID
  #define COLOR_WIFI_MID          255, 255,   0
#endif
#ifndef COLOR_WIFI_HIGH
  #define COLOR_WIFI_HIGH           0, 255,   0
#endif

#define EN  1
#define RU  2
#define HU  3
#define PL  4 
#define NL  5  
#define GR  6  
#define CZ  7  
#define SK  8  
#define UA  9
#define DE  10
#define ES  11
#ifndef LANGUAGE
  #define LANGUAGE EN
#endif

/***** AUTO FADE *****/
#ifndef FADE_ENABLED
  #define FADE_ENABLED 0      // 0 - OFF;  1 - ON
#endif 
#ifndef FADE_START_DELAY
  #define FADE_START_DELAY 60 // delay before start (sec)
#endif
#ifndef FADE_TARGET
  #define FADE_TARGET 50      // target brightness %
#endif
#ifndef FADE_STEP
  #define FADE_STEP 8         // brightness %
#endif
#ifndef FADE_PERIOD
  #define FADE_PERIOD 500     // The time between darkening steps is greater than 499
#endif

/* Ampli power */
#ifndef PWR_AMP                      // "PWR_AMP"
  #define PWR_AMP                255
#endif

#include <SPI.h>
#if !defined(CONFIG_IDF_TARGET_ESP32)
#define VSPI FSPI
#endif

#ifndef SCREENSAVERSTARTUPDELAY
  #define SCREENSAVERSTARTUPDELAY 5
#endif
#ifndef HEADER_TIMEOUT
  #define HEADER_TIMEOUT    5000
#endif
#ifndef USE_OTA
  #define USE_OTA    false
#endif
#ifndef WATCHDOG_INTERVAL
  #define WATCHDOG_INTERVAL    3 //sec.
#endif
//#define OTA_PASS "myotapassword12345"
//#define HTTP_USER "user"
//#define HTTP_PASS "password"
#ifndef WATCHDOG_TASK_SIZE
  #define WATCHDOG_TASK_SIZE    1024*6
#endif
#ifndef WATCHDOG_TASK_PRIORITY
  #define WATCHDOG_TASK_PRIORITY    3
#endif
#ifndef WATCHDOG_TASK_CORE_ID
  #define WATCHDOG_TASK_CORE_ID    1
#endif
#ifndef CONNECTION_TIMEOUT
  #define CONNECTION_TIMEOUT    5700
#endif
#ifndef CONNECTION_TIMEOUT_SSL
  #define CONNECTION_TIMEOUT_SSL    5700
#endif
#ifndef apSsid
  #define apSsid      "VTom_Radio_AP"
#endif
#ifndef apPassword
  #define apPassword  "12345987"
#endif
#ifndef BUFLEN
  #define BUFLEN                   170
#endif

#endif
